import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const registerFormStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingBottom: 0,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    paddingTop: height * 0.03,
    paddingBottom: height * 0.005,
  },
  logoContainer: {
    alignItems: 'center',
  },
  logo: {
    width: width * 0.15,
    height: width * 0.15,
    maxWidth: 60,
    minWidth: 40,
  },
  formContainer: {
    backgroundColor: '#2C2C2C',
    marginHorizontal: width * 0.08,
    borderRadius: width * 0.05,
    paddingHorizontal: width * 0.06,
    paddingVertical: height * 0.03,
    marginTop: height * 0.01,
    marginBottom: height * 0.1,
  },
  title: {
    fontSize: width * 0.07,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: height * 0.008,
  },
  subtitle: {
    fontSize: width * 0.035,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: height * 0.025,
    opacity: 0.8,
  },
  inputContainer: {
    marginBottom: height * 0.015,
  },
  documentContainer: {
    marginBottom: height * 0.015,
  },
  documentLabel: {
    color: '#ffffff',
    fontSize: width * 0.04,
    marginBottom: height * 0.008,
    fontWeight: '500',
  },
  input: {
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    fontSize: width * 0.04,
    color: '#333333',
  },
  inputError: {
    borderWidth: 1,
    borderColor: '#ff4444',
  },
  errorText: {
    color: '#ff4444',
    fontSize: width * 0.035,
    marginTop: height * 0.005,
    marginLeft: width * 0.02,
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  phonePrefix: {
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    marginRight: width * 0.02,
    fontSize: width * 0.04,
    color: '#333333',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  phoneInput: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    fontSize: width * 0.04,
    color: '#333333',
  },
  addressInputContainer: {
    marginBottom: height * 0.025,
  },
  addressInput: {
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    fontSize: width * 0.04,
    color: '#333333',
    marginBottom: height * 0.01,
  },
  addressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addressInputHalf: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    fontSize: width * 0.04,
    color: '#333333',
  },
  addressInputLeft: {
    marginRight: width * 0.02,
  },
  addressInputRight: {
    marginLeft: width * 0.02,
  },
  inputWithLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.015,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  inputWithLocationButtonError: {
    borderColor: '#ff4444',
  },
  addressInputField: {
    flex: 1,
    fontSize: width * 0.04,
    color: '#333333',
    paddingRight: width * 0.02,
  },
  locationButton: {
    backgroundColor: '#B648A0',
    padding: width * 0.025,
    borderRadius: width * 0.025,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: width * 0.08,
    minHeight: width * 0.08,
  },
  locationButtonActive: {
    backgroundColor: '#9A3A7A',
  },
  locationButtonDisabled: {
    backgroundColor: '#666666',
    opacity: 0.7,
  },
  mapPinIcon: {
    width: width * 0.04,
    height: width * 0.05,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPinCircle: {
    width: width * 0.03,
    height: width * 0.03,
    borderRadius: width * 0.015,
    borderWidth: 1.5,
    borderColor: '#ffffff',
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPinInnerDot: {
    width: width * 0.008,
    height: width * 0.008,
    borderRadius: width * 0.004,
    backgroundColor: '#ffffff',
  },
  mapPinTail: {
    position: 'absolute',
    bottom: 0,
    left: '50%',
    marginLeft: -width * 0.006,
    width: 0,
    height: 0,
    borderLeftWidth: width * 0.006,
    borderRightWidth: width * 0.006,
    borderTopWidth: width * 0.012,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#ffffff',
  },
  zipCodeContainer: {
    marginTop: height * 0.02,
    marginBottom: height * 0.015,
  },
  registerButton: {
    backgroundColor: '#B648A0',
    borderRadius: width * 0.03,
    paddingVertical: height * 0.015,
    alignItems: 'center',
    marginBottom: height * 0.02,
    shadowColor: '#B648A0',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  registerButtonDisabled: {
    backgroundColor: '#666666',
    shadowColor: '#666666',
  },
  registerButtonText: {
    color: '#ffffff',
    fontSize: width * 0.05,
    fontWeight: '600',
  },
  backLink: {
    alignItems: 'center',
  },
  backText: {
    color: '#ffffff',
    fontSize: width * 0.04,
  },
  backLinkText: {
    color: '#B648A0',
    fontWeight: '600',
  },
});
