import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const welcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    minWidth: width,
    minHeight: height,
    maxWidth: width * 1.2,
    maxHeight: height * 1.2,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: width * 0.08,
  },
  logo: {
    width: width * 0.3,
    height: width * 0.3,
    maxWidth: 150,
    minWidth: 100,
    marginBottom: height * 0.04,
  },
  title: {
    fontSize: width * 0.08,
    fontWeight: 'bold',
    color: '#B648A0',
    textAlign: 'center',
    marginBottom: height * 0.02,
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingHorizontal: width * 0.06,
    paddingVertical: height * 0.015,
    borderRadius: width * 0.05,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  subtitle: {
    fontSize: width * 0.045,
    color: '#333333',
    textAlign: 'center',
    lineHeight: width * 0.06,
    marginBottom: height * 0.08,
    paddingHorizontal: width * 0.05,
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical: height * 0.015,
    borderRadius: width * 0.05,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  buttonContainer: {
    width: '100%',
    gap: height * 0.02,
  },
  loginButton: {
    backgroundColor: '#B648A0',
    paddingVertical: height * 0.02,
    borderRadius: width * 0.03,
    alignItems: 'center',
    shadowColor: '#B648A0',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  loginButtonText: {
    color: '#ffffff',
    fontSize: width * 0.05,
    fontWeight: '600',
  },
  registerButton: {
    backgroundColor: '#ffffff',
    paddingVertical: height * 0.02,
    borderRadius: width * 0.03,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  registerButtonText: {
    color: '#B648A0',
    fontSize: width * 0.05,
    fontWeight: '600',
  },
});
